
services:
  postgres:
    image: postgres:17.6
    container_name: pg_paperless
    restart: always
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: irf!TIFD1qCO
      POSTGRES_DB: postgres
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: